package com.example.capitales;

import java.util.ArrayList;
import java.util.List;

public class CiudadesUitls {

    public static List<Pais> fillCiudades(){
        List<Pais> ciudades = new ArrayList<>();
        ciudades.add(new Pais("Asia", "Afganistán", "Kabul"));
        ciudades.add(new Pais("Europa", "Albania", "Tirana"));
        ciudades.add(new Pais("África", "Argelia", "Argel"));
        ciudades.add(new Pais("Oceanía", "Samoa", "Apia"));
        ciudades.add(new Pais("Europa", "Andorra", "Andorra la Vella"));
        ciudades.add(new Pais("África", "Angola", "Luanda"));
        ciudades.add(new Pais("América", "Antigua y Barbuda", "Saint John's"));
        ciudades.add(new Pais("Europa", "Armenia", "Ereván"));
        ciudades.add(new Pais("Oceanía", "Australia", "Canberra"));
        ciudades.add(new Pais("Europa", "Austria", "Viena"));
        ciudades.add(new Pais("Asia", "Azerbaiyán", "Bakú"));
        ciudades.add(new Pais("América", "Bahamas", "Nasáu"));
        ciudades.add(new Pais("Asia", "Bangladés", "Dhaka"));
        ciudades.add(new Pais("América", "Barbados", "Bridgetown"));
        ciudades.add(new Pais("Europa", "Bielorrusia", "Minsk"));
        ciudades.add(new Pais("Europa", "Bélgica", "Bruselas"));
        ciudades.add(new Pais("América", "Belice", "Belmopán"));
        ciudades.add(new Pais("África", "Benín", "Porto Novo"));
        ciudades.add(new Pais("Asia", "Bután", "Timbu"));
        ciudades.add(new Pais("América", "Bolivia", "Sucre"));
        ciudades.add(new Pais("Europa", "Bosnia y Herzegovina", "Sarajevo"));
        ciudades.add(new Pais("África", "Botsuana", "Gaborone"));
        ciudades.add(new Pais("América", "Brasil", "Brasilia"));
        ciudades.add(new Pais("Asia", "Brunéi", "Bandar Seri Begawan"));
        ciudades.add(new Pais("Europa", "Bulgaria", "Sofía"));
        ciudades.add(new Pais("África", "Burkina Faso", "Uagadugú"));
        ciudades.add(new Pais("África", "Burundi", "Buyumbura"));
        ciudades.add(new Pais("Asia", "Camboya", "Nom Pen"));
        ciudades.add(new Pais("África", "Camerún", "Yaundé"));
        ciudades.add(new Pais("América", "Canadá", "Ottawa"));
        ciudades.add(new Pais("África", "Cabo Verde", "Praia"));
        ciudades.add(new Pais("África", "República Centroafricana", "Bangui"));
        ciudades.add(new Pais("África", "Chad", "N'Djamena"));
        ciudades.add(new Pais("Europa", "Ciudad del Vaticano", "Ciudad del Vaticano"));
        ciudades.add(new Pais("América", "Chile", "Santiago"));
        ciudades.add(new Pais("Asia", "China", "Pekín"));
        ciudades.add(new Pais("Asia", "Chipre", "Nicosia"));
        ciudades.add(new Pais("África", "Comoras", "Moroni"));
        ciudades.add(new Pais("América", "Costa Rica", "San José"));
        ciudades.add(new Pais("Europa", "Croacia", "Zagreb"));
        ciudades.add(new Pais("América", "Cuba", "La Habana"));
        ciudades.add(new Pais("Europa", "Chipre", "Nicosia"));
        ciudades.add(new Pais("Europa", "Chequia", "Praga"));
        ciudades.add(new Pais("África", "Yibuti", "Yibuti"));
        ciudades.add(new Pais("América", "Dominica", "Roseau"));
        ciudades.add(new Pais("África", "República Dominicana", "Santo Domingo"));
        ciudades.add(new Pais("América", "Ecuador", "Quito"));
        ciudades.add(new Pais("África", "Egipto", "El Cairo"));
        ciudades.add(new Pais("Europa", "Estonia", "Tallin"));
        ciudades.add(new Pais("África", "Etiopía", "Adís Abeba"));
        ciudades.add(new Pais("Oceanía", "Fiyi", "Suva"));
        ciudades.add(new Pais("Europa", "Finlandia", "Helsinki"));
        ciudades.add(new Pais("Europa", "Francia", "París"));
        ciudades.add(new Pais("África", "Gabón", "Libreville"));
        ciudades.add(new Pais("África", "Gambia", "Banjul"));
        ciudades.add(new Pais("Europa", "Georgia", "Tiflis"));
        ciudades.add(new Pais("Europa", "Alemania", "Berlín"));
        ciudades.add(new Pais("África", "Ghana", "Accra"));
        ciudades.add(new Pais("Europa", "Grecia", "Atenas"));
        ciudades.add(new Pais("América", "Granada", "Saint George's"));
        ciudades.add(new Pais("América", "Guatemala", "Ciudad de Guatemala"));
        ciudades.add(new Pais("África", "Guinea", "Conakri"));
        ciudades.add(new Pais("África", "Guinea-Bisáu", "Bisáu"));
        ciudades.add(new Pais("África", "Guinea Ecuatorial", "Malabo"));
        ciudades.add(new Pais("América", "Guyana", "Georgetown"));
        ciudades.add(new Pais("América", "Haití", "Puerto Príncipe"));
        ciudades.add(new Pais("América", "Honduras", "Tegucigalpa"));
        ciudades.add(new Pais("Europa", "Hungría", "Budapest"));
        ciudades.add(new Pais("Europa", "Islandia", "Reikiavik"));
        ciudades.add(new Pais("Asia", "India", "Nueva Delhi"));
        ciudades.add(new Pais("Asia", "Indonesia", "Yakarta"));
        ciudades.add(new Pais("Asia", "Irán", "Teherán"));
        ciudades.add(new Pais("Asia", "Irak", "Bagdad"));
        ciudades.add(new Pais("Europa", "Irlanda", "Dublín"));
        ciudades.add(new Pais("Europa", "Italia", "Roma"));
        ciudades.add(new Pais("África", "Costa de Marfil", "Yamusukro"));
        ciudades.add(new Pais("África", "Jamaica", "Kingston"));
        ciudades.add(new Pais("Asia", "Japón", "Tokio"));
        ciudades.add(new Pais("África", "Jordania", "Amán"));
        ciudades.add(new Pais("Asia", "Kazajistán", "Nur-Sultán"));
        ciudades.add(new Pais("África", "Kenia", "Nairobi"));
        ciudades.add(new Pais("Oceanía", "Kiribati", "Tarawa"));
        ciudades.add(new Pais("África", "Kuwait", "Kuwait"));
        ciudades.add(new Pais("Asia", "Kirguistán", "Biskek"));
        ciudades.add(new Pais("Asia", "Laos", "Vientián"));
        ciudades.add(new Pais("Europa", "Letonia", "Riga"));
        ciudades.add(new Pais("Asia", "Líbano", "Beirut"));
        ciudades.add(new Pais("África", "Lesoto", "Maseru"));
        ciudades.add(new Pais("África", "Liberia", "Monrovia"));
        ciudades.add(new Pais("África", "Libia", "Trípoli"));
        ciudades.add(new Pais("Europa", "Liechtenstein", "Vaduz"));
        ciudades.add(new Pais("Europa", "Lituania", "Vilna"));
        ciudades.add(new Pais("Europa", "Luxemburgo", "Luxemburgo"));
        ciudades.add(new Pais("Europa", "Macedonia del Norte", "Skopie"));
        ciudades.add(new Pais("África", "Madagascar", "Antananarivo"));
        ciudades.add(new Pais("África", "Malaui", "Lilongüe"));
        ciudades.add(new Pais("Asia", "Malasia", "Kuala Lumpur"));
        ciudades.add(new Pais("Asia", "Maldivas", "Malé"));
        ciudades.add(new Pais("África", "Malí", "Bamako"));
        ciudades.add(new Pais("Europa", "Malta", "La Valeta"));
        ciudades.add(new Pais("África", "Mauritania", "Nuakchot"));
        ciudades.add(new Pais("África", "Mauricio", "Port Louis"));
        ciudades.add(new Pais("América", "México", "Ciudad de México"));
        ciudades.add(new Pais("Oceanía", "Micronesia", "Palikir"));
        ciudades.add(new Pais("Europa", "Moldavia", "Chisináu"));
        ciudades.add(new Pais("Europa", "Mónaco", "Mónaco"));
        ciudades.add(new Pais("Asia", "Mongolia", "Ulán Bator"));
        ciudades.add(new Pais("Europa", "Montenegro", "Podgorica"));
        ciudades.add(new Pais("África", "Marruecos", "Rabat"));
        ciudades.add(new Pais("África", "Mozambique", "Maputo"));
        ciudades.add(new Pais("África", "Namibia", "Windhoek"));
        ciudades.add(new Pais("Oceanía", "Nauru", "Yaren"));
        ciudades.add(new Pais("Asia", "Nepal", "Katmandú"));
        ciudades.add(new Pais("Oceanía", "Nueva Zelanda", "Wellington"));
        ciudades.add(new Pais("África", "Níger", "Niamey"));
        ciudades.add(new Pais("África", "Nigeria", "Abuya"));
        ciudades.add(new Pais("Europa", "Noruega", "Oslo"));
        ciudades.add(new Pais("Asia", "Omán", "Mascate"));
        ciudades.add(new Pais("Asia", "Pakistán", "Islamabad"));
        ciudades.add(new Pais("Oceanía", "Palaos", "Melekeok"));
        ciudades.add(new Pais("América", "Panamá", "Ciudad de Panamá"));
        ciudades.add(new Pais("Oceanía", "Papúa Nueva Guinea", "Port Moresby"));
        ciudades.add(new Pais("América", "Paraguay", "Asunción"));
        ciudades.add(new Pais("América", "Perú", "Lima"));
        ciudades.add(new Pais("Europa", "Polonia", "Varsovia"));
        ciudades.add(new Pais("Europa", "Portugal", "Lisboa"));
        ciudades.add(new Pais("Europa", "Catar", "Doha"));
        ciudades.add(new Pais("Europa", "Rumania", "Bucarest"));
        ciudades.add(new Pais("Europa", "Rusia", "Moscú"));
        ciudades.add(new Pais("África", "Ruanda", "Kigali"));
        ciudades.add(new Pais("África", "San Cristóbal y Nieves", "Basseterre"));
        ciudades.add(new Pais("Oceanía", "Samoa", "Apia"));
        ciudades.add(new Pais("Europa", "San Marino", "San Marino"));
        ciudades.add(new Pais("América", "San Vicente y las Granadinas", "Kingstown"));
        ciudades.add(new Pais("África", "Santa Lucía", "Castries"));
        ciudades.add(new Pais("África", "Santo Tomé y Príncipe", "Santo Tomé"));
        ciudades.add(new Pais("África", "Arabia Saudita", "Riad"));
        ciudades.add(new Pais("África", "Senegal", "Dakar"));
        ciudades.add(new Pais("Europa", "Serbia", "Belgrado"));
        ciudades.add(new Pais("África", "Seychelles", "Victoria"));
        ciudades.add(new Pais("África", "Sierra Leona", "Freetown"));
        ciudades.add(new Pais("Oceanía", "Islas Salomón", "Honiara"));
        ciudades.add(new Pais("África", "Somalia", "Mogadiscio"));
        ciudades.add(new Pais("África", "Sudáfrica", "Pretoria"));
        ciudades.add(new Pais("África", "Sudán del Sur", "Yuba"));
        ciudades.add(new Pais("África", "Sudán", "Jartum"));
        ciudades.add(new Pais("Europa", "Suecia", "Estocolmo"));
        ciudades.add(new Pais("Europa", "Suiza", "Berna"));
        ciudades.add(new Pais("África", "Suazilandia", "Mbabane"));
        ciudades.add(new Pais("Asia", "Siria", "Damasco"));
        ciudades.add(new Pais("Asia", "Tayikistán", "Dusambé"));
        ciudades.add(new Pais("África", "Tanzania", "Dodoma"));
        ciudades.add(new Pais("Asia", "Tailandia", "Bangkok"));
        ciudades.add(new Pais("África", "Togo", "Lomé"));
        ciudades.add(new Pais("Oceanía", "Tonga", "Nuku'alofa"));
        ciudades.add(new Pais("Europa", "Turquía", "Ankara"));
        ciudades.add(new Pais("Asia", "Turkmenistán", "Asjabad"));
        ciudades.add(new Pais("Oceanía", "Tuvalu", "Funafuti"));
        ciudades.add(new Pais("África", "Túnez", "Túnez"));
        ciudades.add(new Pais("Oceanía", "Vanuatu", "Port Vila"));
        ciudades.add(new Pais("América", "Venezuela", "Caracas"));
        ciudades.add(new Pais("Asia", "Vietnam", "Hanói"));
        ciudades.add(new Pais("África", "Yemen", "Saná"));
        ciudades.add(new Pais("África", "Zambia", "Lusaka"));
        ciudades.add(new Pais("África", "Zimbabue", "Harare"));
        return ciudades;
    }
}
